#!/usr/bin/env groovy
pipeline {
    agent { node { 
        label 'UBUNTU-SGX1' 
        def jenkinsFile
        stage('Loading Jenkins file') {            
            jenkinsFile = /SGX1/Jenkinsfile    
        }
        load jenkinsFile
    } }
}
