#!/usr/bin/env groovy
pipeline {
    agent { node { label 'UBUNTU-SGX1' } }
   
    stages {
        
        stage('Loading Jenkins file') {
            def jenkinsFile
            jenkinsFile = /SGX1/Jenkinsfile
            load jenkinsFile
        }
        
        stage('stage one') {
            steps {
                script {
                    tags_extra = "value_1"
                }
                echo "tags_extra: ${tags_extra}"
            }
        }
        stage('stage two') {
            steps {
                echo "tags_extra: ${tags_extra}"
            }
        }
        stage('stage three') {
            when {
                expression { tags_extra != 'bla' }
            }
            steps {
                echo "tags_extra: ${tags_extra}"
            }
        }
    }
}
